#!/bin/bash

if [ "$1" == "" ]; then
		echo "Usage: ./launch.sh <vm-name>"
		echo "Example: ./launch.sh test (it will launch IMG/test/qemu-img-test.img)"
		exit 0
fi

if [ ! -e "IMG/$1/qemu-img-$1.img" ]; then
		echo "VM $1 doesn't exist"
		exit 0
fi

sudo qemu-system-x86_64 --enable-kvm \
		-m 2048	\
		-smp 8	\
		-initrd "/boot/initrd.img-$(uname -r)" \
		-kernel "/boot/vmlinuz-$(uname -r)" \
		-drive file=IMG/"$1"/qemu-img-$1.img,index=0,media=disk,format=raw \
		-append "console=tty0 console=ttyS0 rw root=/dev/sda" \
		-net bridge,br=br0 \
		-net nic \
		-nographic

		#-append console=ttyS0 \
		#-vnc :0
		#-append "root=/dev/ram console=tty0 console=ttyS0 rw" \
		#-initrd "./initramfs-4.9.76+" \
		#-kernel "/home/refone/linux/arch/x86/boot/bzImage" \
		#-initrd "./initrd.img-4.9.76+" \
		#-hda "IMG/$1/qemu-img-$1.img" \
