#!/bin/bash

if [ "$1" == "" ]; then
		echo "Usage: ./launch.sh <vm-name>"
		echo "Example: ./launch.sh test (it will launch IMG/test/qemu-img-test.img)"
		exit 0
fi

if [ ! -e "IMG/$1/qemu-img-$1.img" ]; then
		echo "VM $1 doesn't exist"
		exit 0
fi

kversion=$(uname -r)
# kversion=4.9.76+

sudo qemu-system-x86_64 --enable-kvm \
		-m 2048	\
		-smp 8	\
		-drive file=IMG/"$1"/qemu-img-$1.img,format=raw \
		-kernel "/boot/vmlinuz-$kversion" \
		-initrd "/boot/initrd.img-$kversion" \
		-append "console=tty0 console=ttyS0 rw root=/dev/sda" \
		-net bridge \
		-net nic \
		-nographic

		#-append console=ttyS0 \
		#-vnc :0
		#-append "root=/dev/ram console=tty0 console=ttyS0 rw" \
		#-initrd "./initramfs-4.9.76+" \
		#-kernel "/home/refone/linux/arch/x86/boot/bzImage" \
		#-initrd "./initrd.img-4.9.76+" \
		#-hda "IMG/$1/qemu-img-$1.img" \
		#-drive file="/home/refone/img/ubuntu16.qcow2" \
		#-drive file=IMG/"$1"/qemu-img-$1.img,index=0,media=disk,format=raw \

		# network
		# -netdev bridge,br=br0,id=n1 -device virtio-net,netdev=n1 \
		# -nic user,ipv6=off,model=e1000,mac=0c:c4:7a:9f:b4:62 \
		# -netdev tap,id=nd0,ifname=tap0 -device e1000,netdev=nd0 \
